var test = require('tape')

var incrdecr = require('../index.js')

test('initvalue', function(t){
  var val = incrdecr(1, 0, 10, 5)
  t.ok(val(), 5)
  t.end()
})
test('increments', function(t){
  var val = incrdecr(2, 0, 10, 5)
  val.events.increment()
  t.ok(val(), 7)
  val.events.increment()
  val.events.increment()
  t.ok(val(), 10)
  t.end()
})
test('decrements', function(t){
  var val = incrdecr(2, 0, 10, 5)
  val.events.decrement()
  t.ok(val(), 3)
  val.events.increment()
  val.events.increment()
  t.ok(val(), 0)
  t.end()
})
test('change', function(t){
  var val = incrdecr(2, 0, 10, 5)
  val.events.change(1)
  t.ok(val(), 1)
  val.events.change(-31)
  t.ok(val(), 0)
  val.events.change(100)
  t.ok(val(), 10)
  val.events.change(6)
  t.ok(val(), 6)
  val.events.change('notanumber')
  t.ok(val(), 6)
  t.end()
})
